version: '3'
services:

  php-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80  
      
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: php-app
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASS
    ports:
      - "9906:3306"
    volumes:
      - "../BDD/db.sql:/docker-entrypoint-initdb.d/1.sql"
      
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80

  python:
    image: python:3.9  
    volumes:
      - ../Python/battery.py:/app/battery.py
      - ../Python/device.py:/app/device.py
      - ./start.sh:/app/start.sh
    working_dir: /app
    command: /app/start.sh

      
  grafana:
    image: grafana/grafana:9.1.7
    ports:
      - 8082:3000
