version: '3'
services:

  php-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80  
      
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: php-app
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASS
    ports:
      - "9906:3306"
    volumes:
      - "../BDD/db.sql:/docker-entrypoint-initdb.d/1.sql"
      
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80

  python-device:
    image: python:3.9  
    restart: always
    volumes:
      - ../Python/device.py:/app/device.py
      - ../Test/Test-Device.py:/app/Test-Device.py
    command: >
      /bin/sh -c "
        python3 -m pip install paho-mqtt &&
        pip install cryptography &&
        pip install pymysql &&
        python -u app/device.py 
      "

  python-battery:
    image: python:3.9  
    restart: always
    volumes:
      - ../Python/battery.py:/app/battery.py
      - ../Test/Test-Battery.py:/app/Test-Battery.py
    command: >
      /bin/sh -c "
        python3 -m pip install paho-mqtt &&
        pip install cryptography &&
        pip install pymysql &&
        python -u app/battery.py 
      "